"""Daily TrustPilot brand-page-removal checker.

Detects a brand's TrustPilot review page being fully delisted (distinct
from an individual review's status, which check_review_status.py already
covers) and auto-flags removed_platform_brands the same way a human
checking the Edit Entry modal's checkbox would -- see
docs/superpowers/specs/2026-08-13-automated-brand-page-removal-detection-design.md.

Env vars required:
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
    NOTIFY_BRAND_REMOVED_URL
"""
import argparse
import json
import logging
import os
import subprocess
import time
from datetime import datetime, timezone
from typing import Optional

import requests
from selenium.webdriver.common.by import By

from check_review_status import build_driver  # reuse, don't duplicate proxy rotation

REMOVED_HEADING_TEXT = "This profile has been removed"

# Same four scripts run_weekly_all_platforms.sh's own LOCK_PATTERN waits on
# before it starts -- kept as an identical string so both paths agree on
# what counts as "another scraper process." This script launches its own
# headless Chrome via build_driver() but previously had zero coordination
# with that job, even though both are cron'd for 01:00 UTC and this box has
# a documented history (Task 128) of Chrome sessions crashing/thrashing
# under concurrent load.
OTHER_SCRAPER_LOCK_PATTERN = "check_review_status.py|check_ag_status.py|check_cg_status.py|check_wo_status.py"
SCRAPER_WAIT_POLL_SECONDS = 60


def other_scraper_running() -> bool:
    result = subprocess.run(
        ["pgrep", "-f", "--", OTHER_SCRAPER_LOCK_PATTERN],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    return result.returncode == 0


def wait_for_other_scrapers() -> None:
    while other_scraper_running():
        print(f"Another scraper process is active - waiting {SCRAPER_WAIT_POLL_SECONDS}s...")
        time.sleep(SCRAPER_WAIT_POLL_SECONDS)


def is_brand_page_removed(driver) -> bool:
    """True only if the page's rendered <h1> text exactly matches
    TrustPilot's real delisted-brand heading. Reads Selenium's rendered
    .text, never raw page_source -- the same phrase sits unrendered inside
    TrustPilot's own i18n JSON blob on every page, live or removed, so a
    raw-HTML substring check would false-positive on every brand."""
    try:
        heading = driver.find_element(By.TAG_NAME, "h1").text.strip()
    except Exception:
        return False
    return heading == REMOVED_HEADING_TEXT


_BRAND_URLS_PATH = os.path.join(os.path.dirname(__file__), "brand_urls.generated.json")


def load_brand_urls(path: str = _BRAND_URLS_PATH) -> dict:
    """Load brand URL mappings from the JSON file generated by Task 1."""
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def get_brand_tp_url(brand: str, tab: str, brand_urls: dict) -> Optional[str]:
    """Mirrors src/lib/tab-configs.ts's getBrandTpUrl exactly: a tab-specific
    override in tab_brand_urls wins over the flat brand_tp_urls map."""
    key = brand.strip().lower()
    tab_urls = brand_urls.get("tab_brand_urls", {}).get(tab, {})
    if key in tab_urls:
        return tab_urls[key]
    return brand_urls.get("brand_tp_urls", {}).get(key)


def tab_label(tab: str, brand_urls: dict) -> str:
    """Mirrors src/lib/tabs.ts's tabDisplayName exactly."""
    return brand_urls.get("tab_display_names", {}).get(tab, tab)


SUPABASE_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")

# Same priority order as BRAND_COLS in src/pages/BrandGroup.tsx and
# check_review_status.py -- keep all three in sync.
BRAND_COLS = ["Brands", "Brand Name", "Brand", "Brand / TP URL PAGE", "URL PAGE", "Account Name"]


def find_brand_col(data: dict) -> Optional[str]:
    for col in BRAND_COLS:
        if col in data:
            return col
    return None


def _headers() -> dict:
    return {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
    }


def fetch_all_entries() -> list:
    """GET every entries row's tab/data, paginated (PostgREST caps at 1000/request)."""
    PAGE = 1000
    rows: list = []
    offset = 0
    while True:
        r = requests.get(
            f"{SUPABASE_URL}/rest/v1/entries",
            headers=_headers(),
            params={"select": "id,tab,data", "order": "id", "limit": PAGE, "offset": offset},
        )
        r.raise_for_status()
        batch = r.json()
        rows.extend(batch)
        if len(batch) < PAGE:
            break
        offset += PAGE
    return rows


def distinct_tab_brands(entries: list) -> set:
    pairs = set()
    for row in entries:
        tab = row.get("tab") or ""
        data = row.get("data") or {}
        brand_col = find_brand_col(data)
        brand = (data.get(brand_col) or "").strip() if brand_col else ""
        if tab and brand:
            pairs.add((tab, brand))
    return pairs


def fetch_removed_keys(platform: str) -> set:
    r = requests.get(
        f"{SUPABASE_URL}/rest/v1/removed_platform_brands",
        headers=_headers(),
        params={"select": "tab,brand_key", "platform": f"eq.{platform}"},
    )
    r.raise_for_status()
    return {(row["tab"], row["brand_key"]) for row in r.json()}


def flag_brand_removed(tab: str, brand: str, platform: str) -> None:
    """Same effect as a human checking the Edit Entry modal's box --
    setBrandPlatformRemoved's exact upsert shape (src/lib/queries.ts)."""
    r = requests.post(
        f"{SUPABASE_URL}/rest/v1/removed_platform_brands",
        headers={**_headers(), "Prefer": "resolution=merge-duplicates,return=minimal"},
        params={"on_conflict": "tab,brand_key,platform"},
        json=[{"tab": tab, "brand": brand, "platform": platform, "removed_by": "Automated Check"}],
    )
    r.raise_for_status()


def notify_brand_removed(
    brand: str, tab_label_value: str, platform_short_label: str, removed_at_label: str,
) -> None:
    """Same payload shape src/lib/brandRemovedNotification.ts sends."""
    url = os.environ["NOTIFY_BRAND_REMOVED_URL"]
    r = requests.post(
        url,
        headers={
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "apikey": SUPABASE_KEY,
            "Content-Type": "application/json",
        },
        json={
            "brand": brand,
            "tabLabel": tab_label_value,
            "platformShortLabel": platform_short_label,
            "removedAtLabel": removed_at_label,
        },
    )
    r.raise_for_status()


_error_logger = logging.getLogger("check_brand_page_removed")
_error_logger.setLevel(logging.ERROR)
_handler = logging.FileHandler(os.path.join(os.path.dirname(__file__), "status_check_errors.log"))
_handler.setFormatter(logging.Formatter("%(asctime)s %(message)s"))
_error_logger.addHandler(_handler)

POST_LOAD_SLEEP = 6


def load_page(driver, url: str) -> None:
    driver.get(url)
    time.sleep(POST_LOAD_SLEEP)


def run(dry_run: bool = False, tab_filter: Optional[str] = None) -> dict:
    if "NOTIFY_BRAND_REMOVED_URL" not in os.environ:
        # Validate before any real work starts (network calls, Selenium).
        # notify_brand_removed() reads this env var lazily, per-brand, AFTER
        # flag_brand_removed() has already written the row -- discovering a
        # missing var there would permanently lose that brand's notification,
        # since a flagged (tab, brand) is skipped on every future run and
        # never re-notified even after the var is fixed.
        raise RuntimeError(
            "NOTIFY_BRAND_REMOVED_URL env var is required but not set. "
            "Set it before running -- see scripts/.env.example."
        )
    wait_for_other_scrapers()
    brand_urls = load_brand_urls()
    already_flagged = fetch_removed_keys("tp")
    entries = fetch_all_entries()
    pairs = distinct_tab_brands(entries)
    if tab_filter:
        pairs = {(tab, brand) for tab, brand in pairs if tab == tab_filter}

    summary = {"checked": 0, "newly_flagged": 0, "already_flagged": 0, "no_url": 0, "errors": 0}
    driver = None
    for tab, brand in sorted(pairs):
        brand_key = brand.strip().lower()
        if (tab, brand_key) in already_flagged:
            summary["already_flagged"] += 1
            continue

        url = get_brand_tp_url(brand, tab, brand_urls)
        if not url or "trustpilot.com" not in url:
            # brand_urls.generated.json is the frontend's generic brand-link
            # map, not TrustPilot-only -- tab_brand_urls overrides can point
            # to askgamblers.com/wizardofodds.com for brands/tabs with no TP
            # page at all. Treat those exactly like "no URL configured"
            # rather than running the TP-specific removal check against a
            # page that was never TrustPilot.
            summary["no_url"] += 1
            continue

        if driver is None:
            # headless=True: unlike AG/CG, TrustPilot sits behind no Cloudflare
            # challenge that requires a real display -- the existing weekly
            # job already runs check_review_status.py's TP check with
            # --headless in production (run_weekly_all_platforms.sh) with no
            # issue. Defaulting to headful here would require an Xvfb/DISPLAY
            # setup this script has no reason to depend on.
            driver = build_driver(headless=True)

        summary["checked"] += 1
        try:
            load_page(driver, url)
            removed = is_brand_page_removed(driver)
        except Exception as exc:
            summary["errors"] += 1
            _error_logger.error("[TP-removal] %s -> %r", url, exc)
            continue

        if not removed:
            continue

        summary["newly_flagged"] += 1
        print(f"  REMOVED: {tab} / {brand} -> {url}")
        if dry_run:
            continue
        flag_brand_removed(tab, brand, "tp")
        removed_at_label = datetime.now(timezone.utc).strftime("%d/%m/%Y")
        try:
            notify_brand_removed(brand, tab_label(tab, brand_urls), "TP", removed_at_label)
        except Exception as exc:
            _error_logger.error("[TP-removal-notify] %s/%s -> %r", tab, brand, exc)

    if driver is not None:
        try:
            driver.quit()
        except Exception:
            pass
    return summary


def main() -> None:
    ap = argparse.ArgumentParser(description="Daily TrustPilot brand-page-removal checker")
    ap.add_argument("--tab", help="Restrict to a specific tab name")
    ap.add_argument("--dry-run", action="store_true", help="Print detections without writing/notifying")
    args = ap.parse_args()

    print("Checking TrustPilot brand pages for removal...")
    summary = run(dry_run=args.dry_run, tab_filter=args.tab)
    print(
        f"Checked {summary['checked']}, newly flagged {summary['newly_flagged']}, "
        f"already flagged (skipped) {summary['already_flagged']}, "
        f"no URL {summary['no_url']}, errors {summary['errors']}"
    )


if __name__ == "__main__":
    main()
