"""Daily TrustPilot brand-page-removal checker.

Detects a brand's TrustPilot review page being fully delisted (distinct
from an individual review's status, which check_review_status.py already
covers) and auto-flags removed_platform_brands the same way a human
checking the Edit Entry modal's checkbox would -- see
docs/superpowers/specs/2026-08-13-automated-brand-page-removal-detection-design.md.

Env vars required:
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
    NOTIFY_BRAND_REMOVED_URL
"""
import json
import os
from typing import Optional

from selenium.webdriver.common.by import By

REMOVED_HEADING_TEXT = "This profile has been removed"


def is_brand_page_removed(driver) -> bool:
    """True only if the page's rendered <h1> text exactly matches
    TrustPilot's real delisted-brand heading. Reads Selenium's rendered
    .text, never raw page_source -- the same phrase sits unrendered inside
    TrustPilot's own i18n JSON blob on every page, live or removed, so a
    raw-HTML substring check would false-positive on every brand."""
    try:
        heading = driver.find_element(By.TAG_NAME, "h1").text.strip()
    except Exception:
        return False
    return heading == REMOVED_HEADING_TEXT


_BRAND_URLS_PATH = os.path.join(os.path.dirname(__file__), "brand_urls.generated.json")


def load_brand_urls(path: str = _BRAND_URLS_PATH) -> dict:
    """Load brand URL mappings from the JSON file generated by Task 1."""
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def get_brand_tp_url(brand: str, tab: str, brand_urls: dict) -> Optional[str]:
    """Mirrors src/lib/tab-configs.ts's getBrandTpUrl exactly: a tab-specific
    override in tab_brand_urls wins over the flat brand_tp_urls map."""
    key = brand.strip().lower()
    tab_urls = brand_urls.get("tab_brand_urls", {}).get(tab, {})
    if key in tab_urls:
        return tab_urls[key]
    return brand_urls.get("brand_tp_urls", {}).get(key)


def tab_label(tab: str, brand_urls: dict) -> str:
    """Mirrors src/lib/tabs.ts's tabDisplayName exactly."""
    return brand_urls.get("tab_display_names", {}).get(tab, tab)
