"""Daily TrustPilot brand-page-removal checker.

Detects a brand's TrustPilot review page being fully delisted (distinct
from an individual review's status, which check_review_status.py already
covers) and auto-flags removed_platform_brands the same way a human
checking the Edit Entry modal's checkbox would -- see
docs/superpowers/specs/2026-08-13-automated-brand-page-removal-detection-design.md.

Env vars required:
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
    NOTIFY_BRAND_REMOVED_URL
"""
import json
import os
from typing import Optional

import requests
from selenium.webdriver.common.by import By

REMOVED_HEADING_TEXT = "This profile has been removed"


def is_brand_page_removed(driver) -> bool:
    """True only if the page's rendered <h1> text exactly matches
    TrustPilot's real delisted-brand heading. Reads Selenium's rendered
    .text, never raw page_source -- the same phrase sits unrendered inside
    TrustPilot's own i18n JSON blob on every page, live or removed, so a
    raw-HTML substring check would false-positive on every brand."""
    try:
        heading = driver.find_element(By.TAG_NAME, "h1").text.strip()
    except Exception:
        return False
    return heading == REMOVED_HEADING_TEXT


_BRAND_URLS_PATH = os.path.join(os.path.dirname(__file__), "brand_urls.generated.json")


def load_brand_urls(path: str = _BRAND_URLS_PATH) -> dict:
    """Load brand URL mappings from the JSON file generated by Task 1."""
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def get_brand_tp_url(brand: str, tab: str, brand_urls: dict) -> Optional[str]:
    """Mirrors src/lib/tab-configs.ts's getBrandTpUrl exactly: a tab-specific
    override in tab_brand_urls wins over the flat brand_tp_urls map."""
    key = brand.strip().lower()
    tab_urls = brand_urls.get("tab_brand_urls", {}).get(tab, {})
    if key in tab_urls:
        return tab_urls[key]
    return brand_urls.get("brand_tp_urls", {}).get(key)


def tab_label(tab: str, brand_urls: dict) -> str:
    """Mirrors src/lib/tabs.ts's tabDisplayName exactly."""
    return brand_urls.get("tab_display_names", {}).get(tab, tab)


SUPABASE_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")

# Same priority order as BRAND_COLS in src/pages/BrandGroup.tsx and
# check_review_status.py -- keep all three in sync.
BRAND_COLS = ["Brands", "Brand Name", "Brand", "Brand / TP URL PAGE", "URL PAGE", "Account Name"]


def find_brand_col(data: dict) -> Optional[str]:
    for col in BRAND_COLS:
        if col in data:
            return col
    return None


def _headers() -> dict:
    return {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
    }


def fetch_all_entries() -> list:
    """GET every entries row's tab/data, paginated (PostgREST caps at 1000/request)."""
    PAGE = 1000
    rows: list = []
    offset = 0
    while True:
        r = requests.get(
            f"{SUPABASE_URL}/rest/v1/entries",
            headers=_headers(),
            params={"select": "id,tab,data", "order": "id", "limit": PAGE, "offset": offset},
        )
        r.raise_for_status()
        batch = r.json()
        rows.extend(batch)
        if len(batch) < PAGE:
            break
        offset += PAGE
    return rows


def distinct_tab_brands(entries: list) -> set:
    pairs = set()
    for row in entries:
        tab = row.get("tab") or ""
        data = row.get("data") or {}
        brand_col = find_brand_col(data)
        brand = (data.get(brand_col) or "").strip() if brand_col else ""
        if tab and brand:
            pairs.add((tab, brand))
    return pairs


def fetch_removed_keys(platform: str) -> set:
    r = requests.get(
        f"{SUPABASE_URL}/rest/v1/removed_platform_brands",
        headers=_headers(),
        params={"select": "tab,brand_key", "platform": f"eq.{platform}"},
    )
    r.raise_for_status()
    return {(row["tab"], row["brand_key"]) for row in r.json()}


def flag_brand_removed(tab: str, brand: str, platform: str) -> None:
    """Same effect as a human checking the Edit Entry modal's box --
    setBrandPlatformRemoved's exact upsert shape (src/lib/queries.ts)."""
    r = requests.post(
        f"{SUPABASE_URL}/rest/v1/removed_platform_brands",
        headers={**_headers(), "Prefer": "resolution=merge-duplicates,return=minimal"},
        params={"on_conflict": "tab,brand_key,platform"},
        json=[{"tab": tab, "brand": brand, "platform": platform, "removed_by": "Automated Check"}],
    )
    r.raise_for_status()


def notify_brand_removed(
    brand: str, tab_label_value: str, platform_short_label: str, removed_at_label: str,
) -> None:
    """Same payload shape src/lib/brandRemovedNotification.ts sends."""
    url = os.environ["NOTIFY_BRAND_REMOVED_URL"]
    r = requests.post(
        url,
        headers={
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "apikey": SUPABASE_KEY,
            "Content-Type": "application/json",
        },
        json={
            "brand": brand,
            "tabLabel": tab_label_value,
            "platformShortLabel": platform_short_label,
            "removedAtLabel": removed_at_label,
        },
    )
    r.raise_for_status()
